### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2021.2)

### ISSUE THREAD

**Issue by chenmins** [VueGWT/vue-gwt-intellij-plugin#9]
![微信截图_20220124161815](https://user-images.githubusercontent.com/2321767/150746316-fea9b328-7487-4277-a6b4-f697ad58336b.png)

Thanks!

**Comment by adrienbaron** [comment]
I actually submitted an updated to JetBrains a while back, not sure why it’s not live yet 😅. I’ll attach it on GitHub as a zip so you can get it.

**Comment by adrienbaron** [comment]
@chenmins created [a github release](https://github.com/VueGWT/vue-gwt-intellij-plugin/releases/tag/v0.2.2) for you! You should be able to install it following [this guide](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).
